# Generated by Django 5.0.2 on 2024-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_information',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Student_Image', models.ImageField(default='', max_length=350, upload_to='images')),
            ],
        ),
    ]
