# Generated by Django 5.0.2 on 2024-07-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='Date',
            field=models.DateField(),
        ),
    ]
