# Generated by Django 5.0.2 on 2024-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_information_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=50)),
                ('sign_email', models.CharField(max_length=30)),
                ('sign_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
